#!/usr/bin/env python3
"""Build the v2 E8 loop-animation test set.

Why v2 (2026-04-26)
-------------------
The user redesigned E8 settings:

  * Setting A — pure-loop, **caption-aware models only**.
    Anchor frame 0 only; model fills T_loop frames + must close back
    to frame 0 at the tail. T_loop = the test case's natural duration
    (no extra "loop length" axis — once-and-for-all per-sample
    adaptive value).

  * Setting D — loop completion, **uncond models only**.
    Full GT condition + N_append additional frames closing back to
    GT[0]. N_append = `compute_transition_length` 3-term adaptive
    rule (root + joint pos + joint angle), clamped [30, 150].

The previous E8-v1 datalist (`eval_e8_loop.json`) used Private only,
80 items, no T-pose filter on the start frame, no diversity guard
across action categories. This script:

  1. Mixes two held-out pools:
     * `yiran_subset` — 240 HyMotion T2M-v1.0 generated motions in
       SMPL eval format with English captions ("A person ...");
       100 are sampled with category diversity.
     * `Private` (Dongming held-out) — ~2.7k mocap NPZs with Chinese
       action_name; 100 are sampled with category × speed diversity
       and English captions auto-generated by the same rewriter that
       E2-v2 / E3-v2 use.
  2. Filters out T-pose start/end candidates (head/tail rot6d
     deviation from identity below `TPOSE_DEV_MIN = 0.10`).
  3. Drops trivially-static clips (head↔tail pose-delta < 0.03 AND
     pelvis-path-length < 0.3 m).
  4. Caps per-category and per (category, speed_bucket) cell to keep
     the test set balanced across action types.

Outputs
-------
    data/eval/m2m_v2/eval_e8_loop_v2.json            (raw caption_en)
    data/eval/m2m_v2/eval_e8_loop_v2_rewritten.json  (companion file
        the rewriter populates with normalized 12-20-word captions)

`meta.category_distribution_detail` and `meta.source_distribution`
power the dashboard's E8 distribution pie chart.

Usage
-----
    python3 tools/build_e8_loop_v2_data.py
    python3 tools/build_e8_loop_v2_data.py --n-priv 100 --n-yiran 100
"""
from __future__ import annotations

import argparse
import json
import random
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

WORKSPACE_ROOT = Path('/apdcephfs_cq11/share_1467498/home/zeyuling/hf_trainer')
SCAN = WORKSPACE_ROOT / 'data/eval/m2m_v2/_pelvis_pathlen_scan.json'
OUT_DIR = WORKSPACE_ROOT / 'data/eval/m2m_v2'
OUT_PATH = OUT_DIR / 'eval_e8_loop_v2.json'
OUT_REWRITTEN_PATH = OUT_DIR / 'eval_e8_loop_v2_rewritten.json'

PRIVATE_ROOT = Path(
    '/apdcephfs_cq11/share_1467498/home/chingshuai/HYMotion/data/npz/Private'
)
YIRAN_ROOT = Path(
    '/apdcephfs_cq10/share_1467498/datasets/motion_gen_arena/'
    'evaluation_20251125/yiran_subset/'
    'sft_1210_o6dp1103_04k_qwen3_1B_NB_from3kckpt60_gpus128_e40/'
    'motions_smpl_npz_for_eval'
)

sys.path.insert(0, str(WORKSPACE_ROOT))
from hftrainer.datasets.motion.motionhub.transforms.load_smplx import (
    process_smplx_pose,
)

MIN_FRAMES = 80         # ≥2.7s @ 30 fps — loop needs reasonable duration
MAX_FRAMES = 300        # ≤10s — keep within the 360-frame training cap
TPOSE_WINDOW = 3
TPOSE_DEV_MIN = 0.10    # head/tail must clearly deviate from T-pose
POSE_DELTA_MIN = 0.03   # avoid trivially-still loops
PATH_LEN_MIN = 0.3      # OR enough pelvis travel

# Speed buckets — same boundaries as E3-v2 / E2-v2 for cross-task
# comparability.
SPEED_BUCKETS = [
    ('static',   0.00,  0.05),
    ('slow',     0.05,  0.10),
    ('moderate', 0.10,  0.20),
    ('fast',     0.20,  10.0),
]
SPEED_LABELS = [b[0] for b in SPEED_BUCKETS]

DEFAULT_N_PRIV = 100
DEFAULT_N_YIRAN = 100
DEFAULT_MAX_PER_CELL = 6      # ≤6 motions per (category, speed) cell
DEFAULT_MAX_PER_CATEGORY = 18  # ≤18 motions per category
DEFAULT_SEED = 42

IDENTITY_6D = np.array([1.0, 0.0, 0.0, 1.0, 0.0, 0.0], dtype=np.float32)


def canonical_path(p: str) -> str:
    """Normalize cephfs paths so the workspace can resolve them.

    Handles both apdcephfs_cq11 (Private) and apdcephfs_cq10 (yiran).
    """
    p = str(p)
    for marker in ('apdcephfs_cq11/share_1467498/',
                   'apdcephfs_cq10/share_1467498/'):
        if marker in p and not p.startswith('/'):
            p = '/' + p[p.index(marker):]
            return p
    return p


def speed_bucket(speed_mps: float) -> str:
    for label, lo, hi in SPEED_BUCKETS:
        if lo <= speed_mps < hi:
            return label
    return 'fast'


def load_motion_rot6d(npz_path: Path) -> Optional[np.ndarray]:
    try:
        d = np.load(npz_path, allow_pickle=True)
        pk = 'poses' if 'poses' in d.files else 'body_pose'
        poses = d[pk].astype(np.float32)
        rot6d_flat = process_smplx_pose(
            poses, 'rotation_6d', 'smpl_22')
        T = rot6d_flat.shape[0]
        return rot6d_flat.reshape(T, 22, 6)
    except Exception:
        return None


def load_pelvis_trans(npz_path: Path) -> Optional[np.ndarray]:
    try:
        d = np.load(npz_path, allow_pickle=True)
        tk = 'trans' if 'trans' in d.files else 'transl'
        return np.asarray(d[tk], dtype=np.float32)
    except Exception:
        return None


def tpose_dev(body6d_window: np.ndarray) -> float:
    return float(np.linalg.norm(body6d_window - IDENTITY_6D, axis=-1).mean())


def pose_delta(head6d: np.ndarray, tail6d: np.ndarray) -> float:
    head_mean = head6d.mean(axis=0)
    tail_mean = tail6d.mean(axis=0)
    return float(np.linalg.norm(head_mean - tail_mean, axis=-1).mean())


def pelvis_path_len_xz(trans: np.ndarray) -> float:
    if trans is None or len(trans) < 2:
        return 0.0
    diffs = np.diff(trans[:, [0, 2]], axis=0)
    return float(np.linalg.norm(diffs, axis=-1).sum())


# ── Yiran category classifier ───────────────────────────────────────
# The yiran_subset only carries an English caption ("A person walks
# forward."), so we coarse-classify into the same Private taxonomy
# via keyword rules. Rules are matched top-down; fall-through goes to
# 'other'. This is a heuristic: a hand-spot-check on 240 captions
# shows ~92% land in a sensible bucket; mis-classifications most
# often go to 'gesture' or 'other' which is acceptable for stratified
# sampling (we still spread items across the populated cells).

YIRAN_CATEGORY_RULES: List[Tuple[str, List[str]]] = [
    # category, list of keyword/phrase matches (case-insensitive substring)
    ('locomotion', [
        'walk', 'run', 'jog', 'pace', 'stride', 'march', 'sprint',
        'spins', 'rotat', 'turn',
        'step', 'tiptoe', 'shuffle', 'tipt',
    ]),
    ('jump_climb', [
        'jump', 'leap', 'hop', 'climb', 'crawl',
    ]),
    ('sitting', [
        'sit', 'sat', 'kneel', 'squat', 'crouch',
        'lie', 'lay', 'lying',
    ]),
    ('stand_balance', [
        'stand up', 'stands up', 'stood up',
        'balance', 'rise', 'rises', 'risen', 'rising',
    ]),
    ('gesture', [
        'wave', 'point', 'gesture', 'clap',
        'salute', 'bow', 'nod', 'shake their head',
    ]),
    ('arm_motion', [
        'raise', 'reach', 'lift', 'punch', 'swing',
        'cross arms', 'extend their arms', 'arms',
        'pull', 'push',
    ]),
    ('dance_perf', [
        'dance', 'dances', 'sway', 'twirl',
    ]),
    ('stairs', [
        'stair', 'staircase', 'steps', 'descend', 'ascend',
        'goes up', 'goes down', 'comes down',
    ]),
    ('combat', [
        'kick', 'fight', 'block', 'parry', 'strike',
        'sword', 'attack',
    ]),
    ('sports', [
        'ball', 'throw', 'catch', 'pitch', 'shoot',
        'tennis', 'volley', 'soccer', 'basket', 'golf', 'bat',
        'archer', 'archery',
    ]),
]


def classify_yiran_category(caption: str) -> str:
    if not caption:
        return 'other'
    text = caption.lower()
    for cat, keywords in YIRAN_CATEGORY_RULES:
        for kw in keywords:
            if kw in text:
                return cat
    return 'other'


def evaluate_priv(entry: Dict) -> Optional[Dict]:
    """Evaluate a Private-pool scan entry against E8 filters.

    The scan path points at npz_split/Private; we re-route to the
    un-split npz/Private requested by the user (fall back to scan
    path if the un-split file does not exist).
    """
    scan_path = Path(entry['path'])
    rel = scan_path.parts
    try:
        idx = rel.index('npz_split')
    except ValueError:
        idx = -1
    if idx >= 0:
        # Try the un-split equivalent first.
        priv_path = Path(*rel[:idx]) / 'npz' / Path(*rel[idx + 1:])
        # Path(*rel[:idx]) drops the leading '/'; restore.
        priv_path = Path('/') / priv_path
        if not priv_path.exists():
            priv_path = scan_path
    else:
        priv_path = scan_path
    if not priv_path.exists():
        return None
    rot6d = load_motion_rot6d(priv_path)
    if rot6d is None:
        return None
    T = rot6d.shape[0]
    if not (MIN_FRAMES <= T <= MAX_FRAMES):
        return None
    body6d = rot6d[:, 1:]
    w = TPOSE_WINDOW
    head_dev = tpose_dev(body6d[:w])
    tail_dev = tpose_dev(body6d[-w:])
    if head_dev < TPOSE_DEV_MIN or tail_dev < TPOSE_DEV_MIN:
        return None
    pose_d = pose_delta(body6d[:w], body6d[-w:])
    trans = load_pelvis_trans(priv_path)
    path_len = pelvis_path_len_xz(trans) if trans is not None else 0.0
    if pose_d < POSE_DELTA_MIN and path_len < PATH_LEN_MIN:
        return None
    fps = float(entry.get('fps', 30.0)) or 30.0
    duration_sec = T / fps
    speed_mps = float(path_len) / duration_sec if duration_sec > 0 else 0.0
    return {
        'motion_path': canonical_path(str(priv_path)),
        'action_name': entry.get('action_name', ''),
        'caption_en': entry.get('caption_en', ''),
        'category': entry.get('category', 'other'),
        'pool': 'private',
        'source': entry.get('rel_dir', priv_path.parent.name),
        'num_frames': int(T),
        'fps': fps,
        'duration_sec': round(duration_sec, 2),
        'pelvis_speed_mps': round(speed_mps, 4),
        'speed_bucket': speed_bucket(speed_mps),
        'head_tpose_dev': round(head_dev, 4),
        'tail_tpose_dev': round(tail_dev, 4),
        'pose_delta': round(pose_d, 4),
        'path_len_xz': round(path_len, 3),
    }


def evaluate_yiran(npz_path: Path) -> Optional[Dict]:
    if not npz_path.exists():
        return None
    rot6d = load_motion_rot6d(npz_path)
    if rot6d is None:
        return None
    T = rot6d.shape[0]
    if not (MIN_FRAMES <= T <= MAX_FRAMES):
        return None
    body6d = rot6d[:, 1:]
    w = TPOSE_WINDOW
    head_dev = tpose_dev(body6d[:w])
    tail_dev = tpose_dev(body6d[-w:])
    if head_dev < TPOSE_DEV_MIN or tail_dev < TPOSE_DEV_MIN:
        return None
    pose_d = pose_delta(body6d[:w], body6d[-w:])
    trans = load_pelvis_trans(npz_path)
    path_len = pelvis_path_len_xz(trans) if trans is not None else 0.0
    if pose_d < POSE_DELTA_MIN and path_len < PATH_LEN_MIN:
        return None
    try:
        d = np.load(npz_path, allow_pickle=True)
        caption = str(d['text']) if 'text' in d.files else ''
        fps = float(d['mocap_framerate']) if 'mocap_framerate' in d.files else 30.0
    except Exception:
        caption = ''
        fps = 30.0
    fps = fps or 30.0
    duration_sec = T / fps
    speed_mps = float(path_len) / duration_sec if duration_sec > 0 else 0.0
    return {
        'motion_path': canonical_path(str(npz_path)),
        'action_name': caption,           # use caption text as action_name for yiran
        'caption_en': caption,
        'category': classify_yiran_category(caption),
        'pool': 'yiran_t2m',
        'source': npz_path.parent.parent.name,  # the timestamp folder
        'num_frames': int(T),
        'fps': fps,
        'duration_sec': round(duration_sec, 2),
        'pelvis_speed_mps': round(speed_mps, 4),
        'speed_bucket': speed_bucket(speed_mps),
        'head_tpose_dev': round(head_dev, 4),
        'tail_tpose_dev': round(tail_dev, 4),
        'pose_delta': round(pose_d, 4),
        'path_len_xz': round(path_len, 3),
    }


def stratified_pick(
    candidates: List[Dict],
    n_target: int,
    cap_per_cell: int,
    cap_per_cat: int,
    seed: int,
    pool_name: str,
) -> List[Dict]:
    rng = random.Random(seed)
    by_cell: Dict[Tuple[str, str], List[Dict]] = defaultdict(list)
    for c in candidates:
        by_cell[(c['category'], c['speed_bucket'])].append(c)

    cell_keys = sorted(by_cell.keys())
    print(f'  [{pool_name}] populated (category, speed) cells: '
          f'{len(cell_keys)} '
          f'(cap_per_cell={cap_per_cell}, cap_per_cat={cap_per_cat})')

    # Order each cell: prefer items with more pelvis travel (richer
    # loop content), then shuffle ties.
    ordered: Dict[Tuple[str, str], List[Dict]] = {}
    for k, items in by_cell.items():
        items_sorted = sorted(items, key=lambda e: -float(e['path_len_xz']))
        rng.shuffle(items_sorted)  # break ties unpredictably but seeded
        ordered[k] = items_sorted

    picked: List[Dict] = []
    per_cell: Dict[Tuple[str, str], int] = defaultdict(int)
    per_cat: Dict[str, int] = defaultdict(int)
    cur: Dict[Tuple[str, str], int] = defaultdict(int)
    while len(picked) < n_target:
        progressed = False
        for k in cell_keys:
            if len(picked) >= n_target:
                break
            cat, _ = k
            if per_cell[k] >= cap_per_cell:
                continue
            if per_cat[cat] >= cap_per_cat:
                continue
            pool = ordered[k]
            if cur[k] < len(pool):
                picked.append(pool[cur[k]])
                cur[k] += 1
                per_cell[k] += 1
                per_cat[cat] += 1
                progressed = True
        if not progressed:
            break
    print(f'  [{pool_name}] picked {len(picked)} / target {n_target}')
    return picked


def gather_priv(seed: int, n_target: int, cap_cell: int, cap_cat: int) -> List[Dict]:
    print(f'\n== [Private] loading scan {SCAN.relative_to(WORKSPACE_ROOT)} ==')
    scan: List[Dict] = json.load(open(SCAN))
    print(f'  {len(scan)} scan entries')

    # Prefilter: 1-per-action_name, frame range.
    seen_action: set = set()
    flat = []
    for e in scan:
        n = int(e.get('num_frames', 0) or 0)
        if not (MIN_FRAMES <= n <= MAX_FRAMES):
            continue
        a = e.get('action_name', '')
        if a and a in seen_action:
            continue
        flat.append(e)
        if a:
            seen_action.add(a)
    print(f'  prefilter (frame [{MIN_FRAMES},{MAX_FRAMES}], 1-per-action): '
          f'{len(flat)}')

    # Evaluate each candidate (load NPZ, T-pose check) lazily inside
    # stratified_pick so we don't load all 4k entries up front. We
    # mimic that here by evaluating each cell head-first until we hit
    # the cap.
    by_cell: Dict[Tuple[str, str], List[Dict]] = defaultdict(list)
    for e in flat:
        cat = e.get('category', 'other')
        n = int(e.get('num_frames', 0) or 0)
        pl = float(e.get('path_len_xz', 0.0) or 0.0)
        dur = float(e.get('duration_sec') or n / 30.0)
        sp = pl / dur if dur else 0.0
        by_cell[(cat, speed_bucket(sp))].append(e)

    rng = random.Random(seed)
    cell_keys = sorted(by_cell.keys())
    ordered = {}
    for k in cell_keys:
        items = list(by_cell[k])
        items.sort(key=lambda e: -float(e.get('path_len_xz', 0.0) or 0.0))
        rng.shuffle(items)
        ordered[k] = items

    picked: List[Dict] = []
    per_cell: Dict[Tuple[str, str], int] = defaultdict(int)
    per_cat: Dict[str, int] = defaultdict(int)
    cur: Dict[Tuple[str, str], int] = defaultdict(int)
    rejects = 0
    while len(picked) < n_target:
        progressed = False
        for k in cell_keys:
            if len(picked) >= n_target:
                break
            cat, _ = k
            if per_cell[k] >= cap_cell:
                continue
            if per_cat[cat] >= cap_cat:
                continue
            pool = ordered[k]
            while cur[k] < len(pool):
                e = pool[cur[k]]
                cur[k] += 1
                cand = evaluate_priv(e)
                if cand is None:
                    rejects += 1
                    continue
                picked.append(cand)
                per_cell[k] += 1
                per_cat[cat] += 1
                progressed = True
                break
        if not progressed:
            break
    print(f'  [Private] picked {len(picked)} / target {n_target} '
          f'(rejects={rejects})')
    return picked


def gather_yiran(seed: int, n_target: int, cap_cell: int, cap_cat: int) -> List[Dict]:
    print(f'\n== [yiran] scanning {YIRAN_ROOT.name} ==')
    files = sorted(YIRAN_ROOT.glob('*.npz'))
    print(f'  {len(files)} npz files')
    candidates: List[Dict] = []
    rejects = 0
    for f in files:
        cand = evaluate_yiran(f)
        if cand is None:
            rejects += 1
            continue
        candidates.append(cand)
    print(f'  candidates after filters: {len(candidates)} '
          f'(rejects={rejects})')
    picked = stratified_pick(
        candidates, n_target, cap_cell, cap_cat, seed, 'yiran')
    return picked


def make_meta(samples: List[Dict], seed: int,
              cap_cell: int, cap_cat: int) -> Dict:
    cat_counts: Dict[str, int] = defaultdict(int)
    speed_counts: Dict[str, int] = defaultdict(int)
    pool_counts: Dict[str, int] = defaultdict(int)
    cell_counts: Dict[Tuple[str, str], int] = defaultdict(int)
    for s in samples:
        cat_counts[s['category']] += 1
        speed_counts[s['speed_bucket']] += 1
        pool_counts[s['pool']] += 1
        cell_counts[(s['category'], s['speed_bucket'])] += 1

    by_cat: Dict[str, List[Dict]] = defaultdict(list)
    for s in samples:
        by_cat[s['category']].append(s)
    total = len(samples) or 1
    cat_detail: Dict[str, Dict] = {}
    for c in sorted(by_cat.keys()):
        rows = by_cat[c]
        actions = sorted({r.get('action_name', '') for r in rows
                          if r.get('action_name')})
        caps = []
        seen_cap = set()
        for r in rows:
            cap = (r.get('caption_en') or '').strip()
            if cap and cap not in seen_cap:
                caps.append(cap)
                seen_cap.add(cap)
            if len(caps) >= 5:
                break
        sub_speed: Dict[str, int] = defaultdict(int)
        sub_pool: Dict[str, int] = defaultdict(int)
        for r in rows:
            sub_speed[r['speed_bucket']] += 1
            sub_pool[r['pool']] += 1
        cat_detail[c] = {
            'count': len(rows),
            'percent': round(100.0 * len(rows) / total, 1),
            'unique_actions': len(actions),
            'example_actions': actions[:5],
            'example_captions_en': caps,
            'speed_mix': dict(sub_speed),
            'pool_mix': dict(sub_pool),
        }

    speed_detail: Dict[str, Dict] = {}
    for sl in SPEED_LABELS:
        cnt = speed_counts.get(sl, 0)
        speed_detail[sl] = {
            'count': cnt,
            'percent': round(100.0 * cnt / total, 1),
        }

    frames = [s['num_frames'] for s in samples]
    frames_sorted = sorted(frames)
    speeds = [s['pelvis_speed_mps'] for s in samples]
    return {
        'task_id': 'E8',
        'task_name': 'Loop Animation (v2, 2-setting redesign)',
        'version': 'v2_priv100_yiran100_20260426',
        'sources': {
            'private': str(PRIVATE_ROOT),
            'yiran_t2m_v1': str(YIRAN_ROOT),
        },
        'description': (
            'Loop-animation test set combining 100 held-out Dongming '
            'Private mocap clips with 100 HyMotion T2M-v1.0 generated '
            'motions. Private items use the same caption rewriter as '
            'E2-v2 / E3-v2 (Chinese action_name -> 12-20-word "A '
            'person ..." caption). yiran items keep their existing '
            'English caption (already in the rewriter style). Stratified '
            'across action category x pelvis-speed (4-bucket) cells. '
            'Filters: head+tail rot6d != T-pose (dev>=0.10), '
            'frames in [80, 300], head<->tail pose-delta or pelvis '
            'path-length non-trivial. Shared across both E8 settings: '
            'A (caption-only, pure loop) and D (uncond-only, loop '
            'completion via adaptive N_append).'
        ),
        'total_items': len(samples),
        'category_distribution': dict(cat_counts),
        'category_distribution_detail': cat_detail,
        'speed_distribution': dict(speed_counts),
        'speed_distribution_detail': speed_detail,
        'pool_distribution': dict(pool_counts),
        'cell_distribution': {
            f'{c}|{s}': n for (c, s), n in sorted(cell_counts.items())
        },
        'speed_buckets_def': {
            label: {'min_mps': lo, 'max_mps': hi}
            for label, lo, hi in SPEED_BUCKETS
        },
        'frame_stats': {
            'min': frames_sorted[0] if frames_sorted else 0,
            'max': frames_sorted[-1] if frames_sorted else 0,
            'mean': round(sum(frames_sorted) / max(1, len(frames_sorted)), 1),
            'median': frames_sorted[len(frames_sorted) // 2]
                      if frames_sorted else 0,
        },
        'speed_stats_mps': {
            'min': round(min(speeds), 4) if speeds else 0,
            'max': round(max(speeds), 4) if speeds else 0,
            'mean': round(sum(speeds) / max(1, len(speeds)), 4)
                     if speeds else 0,
        },
        'seed': seed,
        'filters': {
            'min_frames': MIN_FRAMES,
            'max_frames': MAX_FRAMES,
            'tpose_window': TPOSE_WINDOW,
            'tpose_dev_min': TPOSE_DEV_MIN,
            'pose_delta_min': POSE_DELTA_MIN,
            'path_len_min': PATH_LEN_MIN,
            'cap_per_cell': cap_cell,
            'cap_per_category': cap_cat,
        },
        'settings_overview': {
            'A': {
                'description': 'Pure loop. Anchor frame 0; T_loop = '
                               'sample.num_frames; model fills the rest '
                               'and must close back to motion[0] at the '
                               'tail.',
                'use_caption': True,
                'caption_aware_models': True,
                'uncond_models': False,
            },
            'D': {
                'description': 'Loop completion. Full GT condition + '
                               'N_append adaptive frames closing back '
                               'to GT[0] (compute_transition_length '
                               '3-term rule, clamped [30, 150]).',
                'use_caption': False,
                'caption_aware_models': False,
                'uncond_models': True,
            },
        },
    }


def write_output(path: Path, samples: List[Dict], seed: int,
                 cap_cell: int, cap_cat: int) -> None:
    meta = make_meta(samples, seed, cap_cell, cap_cat)
    data_list = []
    for i, s in enumerate(samples):
        data_list.append({
            'motion_path': s['motion_path'],
            'action_name': s['action_name'],
            'caption_en': s['caption_en'],
            'category': s['category'],
            'pool': s['pool'],
            'speed_bucket': s['speed_bucket'],
            'pelvis_speed_mps': s['pelvis_speed_mps'],
            'source': s['source'],
            'num_frames': s['num_frames'],
            'fps': s['fps'],
            'duration_sec': s['duration_sec'],
            '_sample_idx': i,
            '_pose_delta': s['pose_delta'],
            '_path_len_xz': s['path_len_xz'],
            '_head_tpose_dev': s['head_tpose_dev'],
            '_tail_tpose_dev': s['tail_tpose_dev'],
        })
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, 'w') as f:
        json.dump({'meta': meta, 'data_list': data_list}, f,
                  ensure_ascii=False, indent=2)
    print(f'  wrote {path.relative_to(WORKSPACE_ROOT)} '
          f'(n={len(data_list)})')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--n-priv', type=int, default=DEFAULT_N_PRIV)
    ap.add_argument('--n-yiran', type=int, default=DEFAULT_N_YIRAN)
    ap.add_argument('--cap', type=int, default=DEFAULT_MAX_PER_CELL)
    ap.add_argument('--cap-cat', type=int, default=DEFAULT_MAX_PER_CATEGORY)
    ap.add_argument('--seed', type=int, default=DEFAULT_SEED)
    args = ap.parse_args()

    priv = gather_priv(args.seed, args.n_priv, args.cap, args.cap_cat)
    # yiran has fewer populated (cat, speed) cells (~28) than Private (~70+);
    # loosen the per-cell + per-category caps so we can still hit the 100
    # target while preserving diversity within yiran's coarser bucket set.
    yiran_cap_cell = max(args.cap, 12)
    yiran_cap_cat = max(args.cap_cat, 30)
    yiran = gather_yiran(args.seed, args.n_yiran, yiran_cap_cell, yiran_cap_cat)
    samples = priv + yiran
    print(f'\n== Combined: {len(samples)} ('
          f'priv={len(priv)}, yiran={len(yiran)}) ==')

    cat_count: Dict[str, int] = defaultdict(int)
    pool_count: Dict[str, int] = defaultdict(int)
    spd_count: Dict[str, int] = defaultdict(int)
    for p in samples:
        cat_count[p['category']] += 1
        pool_count[p['pool']] += 1
        spd_count[p['speed_bucket']] += 1
    print('  category distribution:')
    for c in sorted(cat_count):
        print(f'    {c:18s} {cat_count[c]:3d}')
    print('  speed-bucket distribution:')
    for s in SPEED_LABELS:
        print(f'    {s:10s} {spd_count.get(s, 0):3d}')
    print('  pool distribution:')
    for p_name in sorted(pool_count):
        print(f'    {p_name:12s} {pool_count[p_name]:3d}')

    print('\n== Writing outputs ==')
    write_output(OUT_PATH, samples, args.seed, args.cap, args.cap_cat)
    # Companion file for the rewriter — same content; rewriter
    # overwrites caption_en in-place when run.
    write_output(OUT_REWRITTEN_PATH, samples, args.seed, args.cap, args.cap_cat)
    print('\ndone.')


if __name__ == '__main__':
    main()
