#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-/apdcephfs_cq11/share_1467498/home/zeyuling/hf_trainer}"

if [[ -z "${TOKEN:-}" ]]; then
  echo "ERROR: TOKEN is not set. Export TOKEN before submitting a Taiji task." >&2
  exit 1
fi

cd "${PROJECT_ROOT}"

TIMESTAMP="$(date +%Y%m%d_%H%M%S)"
TASK_FLAG="${PHYSFLOW_TASK_FLAG:-physflow_kimodo_g1_adv_${TIMESTAMP}}"
OUT_DIR="${PHYSFLOW_OUT_DIR:-output/physflow_kimodo_g1/${TASK_FLAG}}"
GPU_ID="${PHYSFLOW_GPU_ID:-0}"
SEED="${PHYSFLOW_SEED:-42}"
HOST_NUM="${PHYSFLOW_HOST_NUM:-1}"
HOST_GPU_NUM="${PHYSFLOW_HOST_GPU_NUM:-1}"
BUSINESS_FLAG="${PHYSFLOW_BUSINESS_FLAG:-AILab_DHC_DC}"
PYTHON_CMD="${PHYSFLOW_PYTHON_CMD:-/usr/local/bin/python3}"
MODE="${PHYSFLOW_MODE:-adv-sweep}"
PROMPT_BANK="${PHYSFLOW_PROMPT_BANK:-configs/experiments/physflow_kimodo_g1/prompt_bank_v0.jsonl}"
PROMPT_SPLIT="${PHYSFLOW_PROMPT_SPLIT:-smoke}"
MAX_PROMPTS="${PHYSFLOW_MAX_PROMPTS:-3}"
SAMPLES_PER_PROMPT="${PHYSFLOW_SAMPLES_PER_PROMPT:-3}"
HARD_CASES="${PHYSFLOW_HARD_CASES:-8}"
HARD_MIN_SCORE="${PHYSFLOW_HARD_MIN_SCORE:-1.0}"
GOOD_CASES="${PHYSFLOW_GOOD_CASES:-8}"
GOOD_MIN_COMPLETION="${PHYSFLOW_GOOD_MIN_COMPLETION:-0.95}"
GOOD_MAX_JOINT_ERROR="${PHYSFLOW_GOOD_MAX_JOINT_ERROR:-0.7}"
GOOD_MAX_ROOT_TRAJECTORY_ERROR="${PHYSFLOW_GOOD_MAX_ROOT_TRAJECTORY_ERROR:-0.25}"
GOOD_MAX_ROOT_DISPLACEMENT_ERROR="${PHYSFLOW_GOOD_MAX_ROOT_DISPLACEMENT_ERROR:-0.35}"
G1_ONNX="${PHYSFLOW_G1_ONNX:-}"

START_CMD=$(cat <<EOF
cd ${PROJECT_ROOT} && \
export PHYSFLOW_MODE=${MODE} && \
export PHYSFLOW_PROMPT_BANK=${PROMPT_BANK} && \
export PHYSFLOW_PROMPT_SPLIT=${PROMPT_SPLIT} && \
export PHYSFLOW_MAX_PROMPTS=${MAX_PROMPTS} && \
export PHYSFLOW_SAMPLES_PER_PROMPT=${SAMPLES_PER_PROMPT} && \
export PHYSFLOW_HARD_CASES=${HARD_CASES} && \
export PHYSFLOW_HARD_MIN_SCORE=${HARD_MIN_SCORE} && \
export PHYSFLOW_GOOD_CASES=${GOOD_CASES} && \
export PHYSFLOW_GOOD_MIN_COMPLETION=${GOOD_MIN_COMPLETION} && \
export PHYSFLOW_GOOD_MAX_JOINT_ERROR=${GOOD_MAX_JOINT_ERROR} && \
export PHYSFLOW_GOOD_MAX_ROOT_TRAJECTORY_ERROR=${GOOD_MAX_ROOT_TRAJECTORY_ERROR} && \
export PHYSFLOW_GOOD_MAX_ROOT_DISPLACEMENT_ERROR=${GOOD_MAX_ROOT_DISPLACEMENT_ERROR} && \
export PHYSFLOW_G1_ONNX=${G1_ONNX} && \
export PHYSFLOW_PYTHON_CMD=${PYTHON_CMD} && \
bash scripts/embodied/run_kimodo_g1_smoke3_lzy.sh ${OUT_DIR} ${GPU_ID} ${SEED}
EOF
)

python3 tools/taiji_submit.py "${TASK_FLAG}" __UNUSED__ \
  --host_num "${HOST_NUM}" \
  --host_gpu_num "${HOST_GPU_NUM}" \
  --business_flag "${BUSINESS_FLAG}" \
  --start-cmd "${START_CMD}"
